export const projects = [
  {
    id: 1,
    name: 'E-commerce Platform',
    description: 'Building a modern e-commerce platform with React and Laravel',
    status: 'In Progress',
    progress: 65,
    tasks: 24,
    completedTasks: 16,
    priority: 'High',
    deadline: '2024-04-30',
    budget: 50000,
    budgetSpent: 32000,
    team: [
      { id: 1, name: 'John Doe', avatar: '/avatars/john.jpg' },
      { id: 2, name: 'Jane Smith', avatar: '/avatars/jane.jpg' },
      { id: 3, name: 'Mike Johnson', avatar: '/avatars/mike.jpg' },
    ],
    risks: 2,
    lastActivity: '2 hours ago',
  },
  {
    id: 2,
    name: 'Mobile App',
    description: 'Developing a cross-platform mobile application',
    status: 'Planning',
    progress: 15,
    tasks: 18,
    completedTasks: 3,
    priority: 'Medium',
    deadline: '2024-06-15',
    budget: 35000,
    budgetSpent: 5000,
    team: [
      { id: 4, name: 'Sarah Wilson', avatar: '/avatars/sarah.jpg' },
      { id: 5, name: 'Tom Brown', avatar: '/avatars/tom.jpg' },
    ],
    risks: 1,
    lastActivity: '5 hours ago',
  },
];
