export const initialTasks = [
  {
    id: 'F00011',
    name: 'Triển khai chấm công cho bên Nhật',
    type: 'task',
    status: 'IN PROGRESS',
    startDate: '13 Mar, 2025',
    dueDate: '20 Mar, 2025',
    priority: 'Normal',
    parent: '-',
    sprint: 'Sprint 4 - Xử lý feedback bên TKO, Sprint 2',
  },
  {
    id: 'F00012',
    name: 'Web - Feedback Customer Sprint 3 v2.1',
    type: 'task',
    status: 'IN PROGRESS',
    startDate: 'No start date',
    dueDate: 'No due date',
    priority: 'Normal',
    parent: '-',
    sprint:
      'Sprint 2, Sprint 3, Sprint 4 - Xử lý feedback bên TKO, Sprint 5, Sprint 6',
  },
  {
    id: 'F00019',
    name: 'App - Feedback Customer Sprint 3 v2.1',
    type: 'task',
    status: 'DONE',
    startDate: 'No start date',
    dueDate: 'No due date',
    priority: 'Normal',
    parent: '-',
    sprint: 'Sprint 3, Sprint 4 - Xử lý feedback bên TKO',
  },
  {
    id: 'F00046',
    name: 'Note',
    type: 'note',
    status: 'DONE',
    startDate: 'No start date',
    dueDate: 'No due date',
    priority: 'Normal',
    parent: 'F00019',
    sprint: 'Sprint 3, Sprint 4 - Xử lý feedback bên TKO',
  },
  {
    id: 'F00050',
    name: '[App] Điều chỉnh giờ chặn từ 18h30 sang 19h',
    type: 'note',
    status: 'DONE',
    startDate: 'No start date',
    dueDate: '8 Mar, 2025',
    priority: 'Normal',
    parent: 'F00019',
    sprint: 'Sprint 4 - Xử lý feedback bên TKO',
  },
  {
    id: 'F00054',
    name: '[App] Xem được đơn remote/ công tác đã gửi',
    type: 'note',
    status: 'DONE',
    startDate: 'No start date',
    dueDate: '15 Mar, 2025',
    priority: 'Normal',
    parent: 'F00019',
    sprint: 'Sprint 4 - Xử lý feedback bên TKO',
  },
  {
    id: 'F00061',
    name: 'Note',
    type: 'note',
    status: 'TO DO',
    startDate: 'No start date',
    dueDate: 'No due date',
    priority: 'Normal',
    parent: 'Add parent',
    sprint: 'Sprint 4 - Xử lý feedback bên TKO',
  },
  {
    id: 'F00020',
    name: 'Sprint 5',
    type: 'task',
    status: 'IN PROGRESS',
    startDate: 'No start date',
    dueDate: 'No due date',
    priority: 'Normal',
    parent: '-',
    sprint: 'Sprint 6, Sprint 5',
  },
];

export const TASK_STATUSES = {
  TODO: 'TO DO',
  IN_PROGRESS: 'IN PROGRESS',
  DONE: 'DONE',
};

export const TASK_TYPES = {
  TASK: 'task',
  NOTE: 'note',
};

export const SPRINT_OPTIONS = [
  'Sprint 2',
  'Sprint 3',
  'Sprint 4',
  'Sprint 5',
  'Sprint 6',
];
